"""initial schema

Revision ID: a0afc60ea27e
Revises: 
Create Date: 2026-09-12 13:58:07.779151
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0afc60ea27e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_samples_name'), ['name'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'AGENT', 'VIEWER', name='role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('object_kind', sa.String(length=60), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('MODEL', 'MODEL_ARTIFACT', 'DATASET', 'DATASET_VERSION', 'PROMPT', 'SYSTEM_PROMPT', 'EMBEDDING_MODEL', 'VECTOR_INDEX', 'DOCUMENT', 'CORPUS', 'AGENT', 'TOOL', 'MCP_SERVER', 'PACKAGE', 'DEPENDENCY', 'CONTAINER', 'IMAGE', 'RUNTIME', 'API', 'EXTERNAL_SERVICE', name='componentkind', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('digest_expected', sa.String(length=80), nullable=True),
    sa.Column('digest_observed', sa.String(length=80), nullable=True),
    sa.Column('trust_state', sa.Enum('TRUSTED', 'UNTRUSTED', 'UNKNOWN', 'DEGRADED', 'COMPROMISED', 'QUARANTINED', 'RECOVERING', 'RE_CERTIFIED', name='truststate', native_enum=False), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('state_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_components_tenant_kind_name_version', ['tenant_id', 'kind', 'name', 'version'], unique=True)

    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('raw_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('execution_external_id', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.Enum('EXECUTION_STARTED', 'EXECUTION_FINISHED', 'STEP_STARTED', 'STEP_ENDED', 'COMPONENT_OBSERVED', 'OUTPUT_PRODUCED', 'PROMPT_PINNED', name='eventkind', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_events_execution_external_id'), ['execution_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('trust_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('subject_kind', sa.Enum('COMPONENT', 'EXECUTION', 'OUTPUT', name='nodekind', native_enum=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('TRUSTED', 'UNTRUSTED', 'UNKNOWN', 'DEGRADED', 'COMPROMISED', 'QUARANTINED', 'RECOVERING', 'RE_CERTIFIED', name='truststate', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_decisions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_decisions_subject_kind'), ['subject_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_decisions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agent_ref', sa.String(length=240), nullable=False),
    sa.Column('agent_version', sa.String(length=120), nullable=True),
    sa.Column('mode', sa.Enum('SEQUENCE', 'ALLOWED_SET', 'POLICY_ONLY', name='fingerprintmode', native_enum=False), nullable=False),
    sa.Column('doc', sa.JSON(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselines_agent_ref'), ['agent_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONTAINED', 'RECOVERING', 'RESOLVED', name='incidentstatus', native_enum=False), nullable=False),
    sa.Column('root_component_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['root_component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('baseline_id', sa.Uuid(), nullable=True),
    sa.Column('agent_ref', sa.String(length=240), nullable=False),
    sa.Column('agent_version', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='executionstatus', native_enum=False), nullable=False),
    sa.Column('trust_state', sa.Enum('TRUSTED', 'UNTRUSTED', 'UNKNOWN', 'DEGRADED', 'COMPROMISED', 'QUARANTINED', 'RECOVERING', 'RE_CERTIFIED', name='truststate', native_enum=False), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executions_agent_ref'), ['agent_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_executions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quarantine_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('target_kind', sa.Enum('COMPONENT', 'EXECUTION', 'OUTPUT', name='nodekind', native_enum=False), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'WARN', 'QUARANTINE', 'INVALIDATE', 'REQUIRE_APPROVAL', 'ROLLBACK', 'RERUN', 'CERTIFY', name='policyaction', native_enum=False), nullable=False),
    sa.Column('result', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quarantine_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quarantine_actions_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quarantine_actions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.JSON(), nullable=False),
    sa.Column('signature', sa.String(length=200), nullable=False),
    sa.Column('alg', sa.String(length=20), nullable=False),
    sa.Column('key_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='certstatus', native_enum=False), nullable=False),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('src_kind', sa.Enum('COMPONENT', 'EXECUTION', 'OUTPUT', name='nodekind', native_enum=False), nullable=False),
    sa.Column('src_id', sa.Uuid(), nullable=False),
    sa.Column('dst_kind', sa.Enum('COMPONENT', 'EXECUTION', 'OUTPUT', name='nodekind', native_enum=False), nullable=False),
    sa.Column('dst_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('STEP', 'PRODUCED', 'DEPENDS_ON', name='edgekind', native_enum=False), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('expected', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index('ix_edges_dst', ['tenant_id', 'dst_kind', 'dst_id'], unique=False)
        batch_op.create_index('ix_edges_exec', ['tenant_id', 'execution_id'], unique=False)
        batch_op.create_index('ix_edges_src', ['tenant_id', 'src_kind', 'src_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('integrity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('DIGEST_MISMATCH', 'UNEXPECTED_COMPONENT', 'PATH_DEVIATION', 'MISSING_STEP', 'STALE_EVIDENCE', 'FORGED_ATTESTATION', 'MISSING_PROVENANCE', 'PROMPT_MISMATCH', name='integritykind', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('expected', sa.JSON(), nullable=True),
    sa.Column('observed', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrity_events_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('outputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('digest', sa.String(length=80), nullable=False),
    sa.Column('trust_state', sa.Enum('TRUSTED', 'UNTRUSTED', 'UNKNOWN', 'DEGRADED', 'COMPROMISED', 'QUARANTINED', 'RECOVERING', 'RE_CERTIFIED', name='truststate', native_enum=False), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outputs_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outputs_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_outputs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outputs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_outputs_external_id'))
        batch_op.drop_index(batch_op.f('ix_outputs_execution_id'))

    op.drop_table('outputs')
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrity_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integrity_events_execution_id'))

    op.drop_table('integrity_events')
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edges_tenant_id'))
        batch_op.drop_index('ix_edges_src')
        batch_op.drop_index('ix_edges_exec')
        batch_op.drop_index('ix_edges_dst')

    op.drop_table('edges')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_serial'))
        batch_op.drop_index(batch_op.f('ix_certificates_execution_id'))

    op.drop_table('certificates')
    with op.batch_alter_table('quarantine_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quarantine_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quarantine_actions_target_id'))

    op.drop_table('quarantine_actions')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_executions_external_id'))
        batch_op.drop_index(batch_op.f('ix_executions_agent_ref'))

    op.drop_table('executions')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_tenant_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_baselines_agent_ref'))

    op.drop_table('baselines')
    with op.batch_alter_table('trust_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_decisions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_trust_decisions_subject_kind'))
        batch_op.drop_index(batch_op.f('ix_trust_decisions_subject_id'))

    op.drop_table('trust_decisions')
    with op.batch_alter_table('raw_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_events_execution_external_id'))

    op.drop_table('raw_events')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_tenant_id'))

    op.drop_table('policies')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index('ix_components_tenant_kind_name_version')
        batch_op.drop_index(batch_op.f('ix_components_tenant_id'))

    op.drop_table('components')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    op.drop_table('tenants')
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_samples_name'))

    op.drop_table('metric_samples')
    # ### end Alembic commands ###
